[project]
name = "Charge Transfer Analysis"
version = "0.0.1"
description = "A modular Python tool for analyzing electronic charge transfer between molecular domains, derived from the PyBEST framework."
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["h5py","pybest"]
authors = [
    {name = "Julia Szczuczko", email = "j.k.szczuczko@gmail.com"},
]

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"
